# Generated by Django 3.2.1 on 2021-09-01 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='lms_courseware.chapter')),
            ],
            options={
                'verbose_name': 'subchapter',
                'verbose_name_plural': 'subchapters',
            },
        ),
        migrations.CreateModel(
            name='TextSubChapter',
            fields=[
                ('subchapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms_courseware.subchapter')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'textsubchapter',
                'verbose_name_plural': 'textsubchapters',
            },
            bases=('lms_courseware.subchapter',),
        ),
        migrations.CreateModel(
            name='VideoSubChapter',
            fields=[
                ('subchapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms_courseware.subchapter')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'videosubchapter',
                'verbose_name_plural': 'videosubchapters',
            },
            bases=('lms_courseware.subchapter',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('user', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lms_courseware.course'),
        ),
    ]
